### ISSUE TITLE
How to resolve? Trying to use internal database

### ISSUE THREAD

**Issue by wicadmin** [serenader2014/docker-pydio#1]
`
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
database pydio dont exist, try to create database and initialize data...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

`

**Comment by serenader2014** [comment]
Looks like the mysql doesn't running, how do you running this container?

**Comment by wicadmin** [comment]
docker run -dt --name pydio -p 8888:80  \
        -v /storage/myDockers/pydio/personal/:/var/www/pydio-core/data/personal/ \
        -v /storage/myDockers/pydio/mysql:/var/lib/mysql \
        -v /storage/docker/pydio/files/:/var/www/pydio-core/data/files/ \
        2devnull/docker-pydio:latest

**Comment by serenader2014** [comment]
Seems like it's a bug, I'll look into it.
In the mean time, I suggest you use an external mysql container to store the data, it doesn't have this issue.

**Comment by serenader2014** [comment]
Bug fixed. Please pull the latest v2.0.2 tag to have a try. If you want to use the Pydio v6.x version, please pull v1.0.1 tag.

**Comment by wicadmin** [comment]
working now. Thanks. Any update on the file sharing 404 bug? Is it something upstream has to fix or is there a workaround?

**Comment by wicadmin** [comment]
This may be what the issue is. (referred to from a search):
https://pydio.com/en/docs/v6/checking-apis

**Comment by wicadmin** [comment]
Well, I tried your v1.0.1 but the download isn't happening. No 404, but just a blank page when using the generated link.

**Comment by serenader2014** [comment]
The file sharing bug is a Pydio's bug, there is nothing I can do. The `share.php` file located in `data/public` is used to handle the file sharing function, but it was missing in the Pydio's installation package. So you get 404 when you visit a sharing link.

And which browser do you use? I've tested the download link using Chrome many times, it works fine.

**Comment by wicadmin** [comment]
I am using Vivaldi (chromium variant) and Firefox and both does the same thing.

**Comment by serenader2014** [comment]
That's weird, can you post the container's log? 

And BTW, the 404 bug turns out it wasn't the Pydio's bug, since v7.x they don't rely on `share.php` any more. I'll find some time to fix this bug.

**Comment by serenader2014** [comment]
The file sharing issue was fixed in 3a478810255bff93978036b5f2956e21e9dc5333 , you can pull the latest image or v2.0.3 tag to have a try.

**Comment by wicadmin** [comment]
thanks, but I decided to use their [repo](https://pydio.com/en/docs/v7/debianubuntu-systems) and make my own [image](https://github.com/2devnull/docker-pydio/blob/master/Dockerfile).

**Comment by serenader2014** [comment]
That's fine :)
I'm closing this issue since the problem have been solved.
